version: '3.7'

services:
  db_mysql:
    image: mysql:8.0.31
    container_name: mysql8
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    command: --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    volumes:
      - ${MYSQL_VOLUMES_DATA}:/var/lib/mysql
    networks:
      - mysql

  db_redis:
    image: redis:7
    container_name: redis7
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ${REDIS_VOLUMES_DATA}:/data
    command: /bin/bash -c "redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes"
    networks:
      - redis

networks:
  redis:
  mysql:
